"""empty message

Revision ID: 606bd6d68966
Revises: a6a7f74851ca
Create Date: 2023-03-18 00:47:03.008854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606bd6d68966'
down_revision = 'a6a7f74851ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('henhoun', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('henhoun')

    # ### end Alembic commands ###
